# Generated by Django 6.1 on 2026-10-09 12:46

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('product_code', models.SlugField(help_text='Stable code shared with the licensing system. Do not change after release.', unique=True)),
                ('summary', models.CharField(max_length=300)),
                ('body', wagtail.fields.StreamField([('heading', 0), ('rich_text', 1), ('image', 2), ('video', 3), ('callout', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'ul', 'ol', 'blockquote', 'hr']}), 2: ('wagtail.images.blocks.ImageBlock', [], {}), 3: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Paste a YouTube or Vimeo URL.'}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('note', 'Note'), ('tip', 'Tip'), ('warning', 'Warning')]}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol']}), 7: ('wagtail.blocks.StructBlock', [[('style', 4), ('title', 5), ('text', 6)]], {})})),
                ('status', models.CharField(choices=[('coming_soon', 'Coming soon'), ('available', 'Available'), ('discontinued', 'Discontinued')], default='coming_soon', max_length=20)),
                ('current_version', models.CharField(blank=True, max_length=40)),
                ('download_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=False, help_text='Only explicitly published products appear on the public website.')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('search_description', models.CharField(blank=True, max_length=170)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'ordering': ('display_order', 'name', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='ProductGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField()),
                ('kind', models.CharField(choices=[('manual', 'Manual'), ('training', 'Training'), ('video', 'Video guide')], default='manual', max_length=20)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('body', wagtail.fields.StreamField([('heading', 0), ('rich_text', 1), ('image', 2), ('video', 3), ('callout', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'ul', 'ol', 'blockquote', 'hr']}), 2: ('wagtail.images.blocks.ImageBlock', [], {}), 3: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Paste a YouTube or Vimeo URL.'}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('note', 'Note'), ('tip', 'Tip'), ('warning', 'Warning')]}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol']}), 7: ('wagtail.blocks.StructBlock', [[('style', 4), ('title', 5), ('text', 6)]], {})})),
                ('is_published', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('search_description', models.CharField(blank=True, max_length=170)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='products.product')),
            ],
            options={
                'ordering': ('display_order', 'title', 'pk'),
                'constraints': [models.UniqueConstraint(fields=('product', 'slug'), name='unique_product_guide_slug')],
            },
        ),
    ]
