# Generated by Django 6.1 on 2026-10-09 12:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('key_hint', models.CharField(editable=False, max_length=24)),
                ('term', models.CharField(choices=[('14_days', '14 days'), ('1_month', '1 month'), ('3_months', '3 months'), ('1_year', '1 year'), ('lifetime', 'Lifetime')], max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=160)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(choices=[('enabled', 'Enabled'), ('suspended', 'Suspended'), ('revoked', 'Revoked')], default='enabled', max_length=20)),
                ('max_activations', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-issued_at',),
            },
        ),
        migrations.CreateModel(
            name='LicensedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(help_text='Must match the public product code.', unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='LicenseActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_id', models.CharField(max_length=128)),
                ('device_fingerprint_hash', models.CharField(max_length=64)),
                ('plugin_version', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('last_validated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activations', to='licensing.license')),
            ],
            options={
                'ordering': ('-activated_at',),
            },
        ),
        migrations.AddField(
            model_name='license',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='licensing.licensedproduct'),
        ),
        migrations.CreateModel(
            name='LicenseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('activate', 'Activated'), ('validate', 'Validated'), ('deactivate', 'Deactivated'), ('reject', 'Rejected')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=120)),
                ('remote_address_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='licensing.licenseactivation')),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='licensing.license')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='licenseactivation',
            constraint=models.UniqueConstraint(fields=('license', 'installation_id'), name='unique_license_installation'),
        ),
    ]
