# Generated by Django 6.1 on 2026-08-25 13:30

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_studies', '0002_casestudypage_created_on_casestudyimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Case study tag',
                'verbose_name_plural': 'Case study tags',
            },
        ),
        migrations.CreateModel(
            name='CaseStudyPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='case_studies.casestudypage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_study_pages', to='case_studies.casestudytag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='casestudypage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='case_studies.CaseStudyPageTag', to='case_studies.CaseStudyTag', verbose_name='Tags'),
        ),
    ]
