# Generated by Django 6.1 on 2026-08-26 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_studies', '0004_remove_casestudypage_results_casestudyresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestudypage',
            name='project_type',
        ),
    ]
