# Generated by Django 6.1 on 2026-08-26 11:37

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_studies', '0005_remove_casestudypage_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudypage',
            name='challenge',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='casestudypage',
            name='solution',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='casestudypage',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
