# Generated by Django 6.1 on 2026-10-05 12:00

import django.db.models.deletion
import modelsearch.index
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_studies', '0006_alter_casestudypage_challenge_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('name', models.CharField(blank=True, help_text='Optional. Leave blank to attribute the testimonial to the organization.', max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('approved_for_publication', models.BooleanField(default=False, help_text='Confirm that TopMap has permission to publish this testimonial.')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['display_order', 'pk'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
    ]
