# Generated by Django 6.1 on 2026-10-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_studies', '0007_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='organization',
            field=models.CharField(blank=True, help_text='Optional. Leave both name and organization blank for Anonymous.', max_length=255),
        ),
    ]
