"""Public service content shared by pages, navigation, metadata and the sitemap."""
SERVICES = {
    "gis-data-conversion": {
        "name": "GIS data conversion",
        "title": "CAD & Survey Data to GIS Conversion",
        "description": "Turn CAD drawings, survey descriptions and disconnected spatial files into structured GIS data. Discuss inputs, coordinate systems and deliverables with TopMap Solutions.",
        "headline": "Turn disconnected files into usable GIS data.",
        "summary": "Bring CAD drawings, technical descriptions and existing spatial files into a consistent format your team can work with.",
        "problem": "A drawing can look complete and still be difficult to use in GIS. Layers, coordinates and attributes need to agree before the data can support a shared workflow.",
        "inputs": ["CAD drawings or existing spatial datasets", "Technical descriptions and available reference information", "Your target coordinate system, format and intended use"],
        "outputs": ["GIS layers in the agreed format and coordinate system", "An agreed attribute structure for the converted data", "A record of source issues and items requiring clarification"],
        "fit": "For land teams, surveyors, engineering firms and organizations moving from drawings or isolated files to GIS.",
        "boundary": "Conversion cannot resolve missing survey evidence by itself. We agree how to handle incomplete descriptions and uncertain source information before processing.",
    },
    "spatial-data-validation": {
        "name": "Spatial data cleaning & validation",
        "title": "Spatial & Parcel Data Cleaning and Validation",
        "description": "Identify geometry, attribute and consistency issues in GIS datasets. Scope parcel and spatial data cleaning with documented checks and reviewable outputs.",
        "headline": "Know where your spatial data needs attention.",
        "summary": "Find inconsistent attributes, duplicate records and geometry issues before they spread into maps, reports and everyday decisions.",
        "problem": "When teams combine datasets from different sources, gaps and conflicting records are easy to miss. A repeatable review makes those issues visible and helps prioritize corrections.",
        "inputs": ["Existing GIS layers and attribute tables", "Reference datasets and known problem examples", "Your validation rules and intended business workflow"],
        "outputs": ["Reviewed layers with agreed corrections applied", "An issue register separating corrected and unresolved items", "Documented checks your team can use during handover"],
        "fit": "For assessor and planning offices, engineering teams and organizations maintaining spatial records across multiple sources.",
        "boundary": "Data validation checks agreed rules; it does not certify ownership, legal boundaries or field accuracy. Issues needing a survey or domain decision are flagged for your team.",
    },
    "web-gis-development": {
        "name": "Web GIS & workflow consulting",
        "title": "Web GIS Development & GIS Workflow Consulting",
        "description": "Plan and build browser-based GIS workflows for maps, spatial records and shared access. Define users, data, integrations and handover with TopMap Solutions.",
        "headline": "Put maps and spatial records into your team's workflow.",
        "summary": "Move beyond files on individual computers with a web GIS built around the people who need to find, review and use your data.",
        "problem": "A shared map is useful when it answers real questions. We start with your users, data readiness and daily tasks, then define the smallest useful implementation.",
        "inputs": ["Your current datasets and systems", "User roles, recurring tasks and access requirements", "Hosting, integration and maintenance constraints"],
        "outputs": ["An agreed workflow and implementation scope", "A browser-based mapping application for the agreed use cases", "Deployment and handover requirements defined with your team"],
        "fit": "For land-management, planning and infrastructure teams that need a shared way to access and work with spatial information.",
        "boundary": "Hosting, integrations, training and ongoing support are scoped explicitly. A project discussion establishes what is feasible before delivery commitments are made.",
    },
}
